### ISSUE TITLE
export tsv --select

### ISSUE THREAD

**Issue by felixlohmeier** [opencultureconsulting/orcli#116]
```yaml
        flags:
          - long: --select
            help: filter result set to one or more columns
            repeatable: true
```
